### ISSUE TITLE
Snes9x newest version only seening a black screen 

### ISSUE THREAD

**Issue by rdb1200** [LeHulk1/RandoBlazer#1]
i clip from my twitch but when opening the seed randoblazer on version 1,5,5 snes 9x black screens i have tryed multi seed its not working

**Comment by LeHulk1** [comment]
Hi, sorry I'm only seeing this now.
Several people have had this issue, maybe you are not using the correct version of the original U rom. Try to download it from a different site. If you still have trouble, don't hesitate to contact me on discord (Le Hulk#2931).

**Comment by LeHulk1** [comment]
Could you please try again with RandoBlazer version 0.4a? It should now work with headered ROMs so hopefully it can fix your problem.

**Comment by rdb1200** [comment]
it works perfectly now now with snes9xx thanks alot

**Comment by LeHulk1** [comment]
No problem, glad it's now solved. Enjoy the rando!
